# Site settings
name: Jueying Li
title: Jueying Li | Computer & Information Communication Engineering
email: dlrkrdud@163.com
url: "https://rkrdudstar.github.io"
baseurl: ""
repository: Rkrdudstar/rkrdudstar.github.io
github_username: Rkrdudstar

# Social Links
social:
  - name: GitHub
    url: "https://github.com/Rkrdudstar"
  - name: LinkedIn
    url: "https://www.linkedin.com/in/jueying-li"
  - name: WeChat
    url: "https://weixin.qq.com"

# Build settings
theme: modern-resume-theme

# Personal Info
description: "Doctoral researcher in Computer & Information Communication Engineering at Konkuk University. Specializing in cloud computing, AI, distributed systems, and UAV digital twin research."

# Sections
content:
  - title: Education
    layout: list
    content:
      - title: "Konkuk University, Ph.D. in Computer & Information Communication Engineering"
        sub_title: "Seoul, South Korea | Aug 2017 - Feb 2025"
        description: "Courses: Machine Learning, Multiagent Systems, Smart City, Advanced Topics in Distributed Computing, Development of Distributed Applications, Mobile Communication, Multimedia Network, Internet of Intelligent Things, Software Modeling, Professional Industry Practice."
      - title: "Konkuk University, Master of Philosophy in Computer & Information Communication Engineering"
        sub_title: "Seoul, South Korea | Aug 2015 - Aug 2017"
        description: "Courses: Advanced Operating Systems, Network Architecture, Next Generation System, Distributed Information Systems, Development of Distributed Applications, Mobile Communication, Virtual Reality Advanced Topics In, Pervasive Interfaces."
      - title: "Shandong University, Bachelor of Software Engineering"
        sub_title: "Shandong, China | Sep 2010 - Jun 2015"
        description: "Courses: C Programming, Data Structures & Algorithms, Operating Systems, Computer Networks, Software Engineering, Database Systems, Java Programming."

  - title: Internship Experience
    layout: list
    content:
      - title: "Miryo-Vision, Front-End and Back-End Development Engineer"
        sub_title: "Seoul, South Korea | Jul 2018 - Sep 2019"
        description: |
          - Led development of Garment Production Data Management System (Spring Boot + Vue).
          - Defined standardized API protocols and optimized communication.
          - Assisted in multi-node deployment with Docker/Kubernetes.
          - Contributed to Prometheus + Grafana monitoring platform.

  - title: Project Experience
    layout: list
    content:
      - title: "UAV Digital Twin Project, Institute of Aerospace and Aeronautics, Konkuk University, Researcher"
        sub_title: "Seoul, South Korea | Oct 2021 – Present"
        description: |
          - Contributed to a 10-year national key project on UAV digital twin R&D.
          - Led OpenStack cloud architecture design.
          - Developed FastAPI backend modules.
          - Integrated Unreal Engine (UE) 3D simulation environment.
          - Drove CI/CD pipeline implementation.
      - title: "LLM and Multi-Agent AI Edge-Cloud Collaboration Project in Smart City Public Security (Government-funded Project), Researcher"
        sub_title: "Seoul, South Korea | Oct 2022 - Feb 2025"
        description: |
          - Participated in a five-year national smart city initiative.
          - Led OpenStack cloud architecture design and server development.
          - Built robot simulation environment with Gazebo and ROS.
          - Spearheaded elderly care functionality.
          - Developed real-time data processing pipeline with Kafka and Spark.
      - title: "High Performance Hybrid Cloud Computing Technology Development Project for AI Information Services (National Project), Researcher"
        sub_title: "Seoul, South Korea | Dec 2016 - Feb 2022"
        description: |
          - Developed a high-performance hybrid cloud platform.
          - Automated deployment processes using FAI tools.
          - Built OpenStack-based hybrid cloud platform.
          - Developed VM lifecycle management tool with Ansible/Terraform.

  - title: Papers & Conferences
    layout: list
    content:
      - title: "Optimization of Character Animation Design and Motion Synthesis in Film and TV Media Based on Data Mining"
        authors: "Meng, Xiao, and Jueying Li"
        year: "2024"
      - title: "STaaS: Cost Effective and Scalable Union Mounting in ICP for Aerospace Applications"
        authors: "Sakthivel, V., Li, J., Min, D., Lee, J. W., & Choi, E."
        conference: "2024 International Conference on Green Energy, Computing and Sustainable Technology (GECOST)"
        pages: "pp. 334-338"
        publisher: "IEEE"
        year: "2024"
      - title: "Software aging effects on kubernetes in container orchestration systems for digital twin cloud infrastructures of urban air mobility"
        authors: "Costa, J., Matos, R., Araujo, J., Li, J., Choi, E., Nguyen, T. A., … & Min, D."
        journal: "Drones"
        volume: "7(1)"
        page: "35"
        year: "2023"
      - title: "Auto-Provisioning of UAV Industry Cloud Platform for Intelligent Multi UAVs Simulation"
        authors: "Li, Jueying, et al."
        conference: "15th International Conference on Advanced Computational Intelligence (ICACI)"
        publisher: "IEEE"
        year: "2023"
      - title: "Cloud-in-the-loop simulation: A cloud-based digital twin HW/SW framework for multi-mode AI control simulation of eVTOL KADA-UAM Personal Aerial Vehicles"
        authors: "Nguyen, T. A., Li, J., Jang, M., Maw, A. A., Pham, V., & Lee, J. W."
        conference: "한국항공우주학회 학술발표회 초록집"
        pages: "138-139"
        year: "2022"
      - title: "UAV Oriented Container based Reconfigurable Federated Fog/Edge Cluster System"
        authors: "Li, Jueying, et al."
        conference: "한국항공우주학회 학술발표회 초록집"
        pages: "566-567"
        year: "2023"
      - title: "Customer Feedback Automation and Classification using Sentiment Analysis, Robotic Process Automation and Uipath"
        year: "2023"
      - title: "System Dynamics Model of Urban Transportation System"
        book: "Urban Air Mobility"
        pages: "pp.53-74"
        year: "2024"
        doi: "10.1201/9781003339953-3"
      - doi: "10.13052/rp-9788770040723.175"

  - title: Languages & Skills
    layout: text
    content: |
      Languages: Chinese (Native), English (Proficient, CET-4, CET-6), Korean (Proficient, TOPIK5, C1)
      Technical Skills: Microsoft Office, OpenStack, KVM, libvirt, Ceph, Xen, FAI, Kubernetes, Docker, PyTorch, TensorFlow, LLM, Terraform, Ansible, UnrealEngine, PX4, QGroundControl.

  - title: Interests
    layout: text
    content: |
      Games, Roller Skating

# Theme Settings
darkmode: true
favicon: images/favicon.ico
